### ISSUE TITLE
Unhandled parse errors

### ISSUE THREAD

**Issue by Questdoino** [pierremolinaro/canfd-plugin-for-saleae-logic-analyzer#1]
Logic 2.3.16
Trying to parse a log from a real CAN-FD bus. Seems like plugin has not correct search of SOF approach in ISO mode, because after 1-st parse error no frames can be detected. In non-ISO mode all frames detected with wrong checksum.

**Comment by pierremolinaro** [comment]
Hello,

My canfd-plugin-for-saleae-logic-analyzer plugin is a work in progress, I know it fails even in simulation mode. Unfortunately, I currently do not have the time to work on it.

Pierre Molinaro
