### ISSUE TITLE
Release package with builded extension

### ISSUE THREAD

**Issue by ZiGaMi** [pierremolinaro/canfd-plugin-for-saleae-logic-analyzer#3]
Hello guys!

Really appreciating your work done for CAN-FD decoding and sharing with the others!

However it would be nice to have pre-builded extension in a release package. That will reduce time for individuals as me, that do not have a Salea SDK C++ toolchain setup. 

Is this something that we can expect in the future releases?

Is it possible to get a .dll extension builded on Win10? 

Thank you again and keep up the good work!

**Comment by pierremolinaro** [comment]
Hello,

Thank you very much for your message !

The compiled libraries are available from the GitHub page :

1) click on "5 tags"
￼

2) click on "Download" of the 1.1.4 realease
￼

3) Download "analyser.zip"
￼


Decompress analyzer.zip, you will find libraries for macos, Linux and Windows. I have not checked the Windows one, I work on Mac.

I agree the binaries are difficult to find, I will investigate to make them more accessible.

Best Regards,

Pierre

**Comment by pierremolinaro** [comment]
With the images:

1) click on "5 tags"
<img width="640" alt="GraphiqueCollé-1" src="https://github.com/pierremolinaro/canfd-plugin-for-saleae-logic-analyzer/assets/19705044/177ef4d2-0ff5-48c7-a909-27fcdea6ca0a">

2) click on "Download" of the 1.1.4 realease
<img width="486" alt="GraphiqueCollé-2" src="https://github.com/pierremolinaro/canfd-plugin-for-saleae-logic-analyzer/assets/19705044/7987ffa2-65a5-40d8-99f5-9d2e16e3468c">

3) Download "analyser.zip"
<img width="237" alt="GraphiqueCollé-3" src="https://github.com/pierremolinaro/canfd-plugin-for-saleae-logic-analyzer/assets/19705044/dcc9b668-207b-4e41-ab46-8aeb027fbf89">

**Comment by ZiGaMi** [comment]
I've try it and it works! Amazing, you save me a lot of time here!

Thank you again!
